<script>
    if (!Mage.Cookies.get('seenModal') || <?php echo Mage::getStoreConfig('cms/modal/skip_cookie_check') ?>) {
        // Cookie user
        var today = new Date();
        today.setTime(today.getTime());
        var duration = 1000 * 60 * 60 * 24 * <?php echo (int) Mage::getStoreConfig('cms/modal/cookie_duration')?>;
        var expireDate = new Date(today.getTime() + duration);
        Mage.Cookies.expires = expireDate;
        Mage.Cookies.set('seenModal', 1);
        
        // Show modal
        modal = new Window({
            width: window.innerWidth,
            height: window.innerHeight,
            zIndex: <?php echo Mage::getStoreConfig('cms/modal/modalZindex'); ?>
        });
        modal.getContent().update('<?php echo str_replace(array("\r", "\n"), "", addslashes($this->getLayout()->createBlock("cms/block")->setBlockId(Mage::getStoreConfig("cms/modal/block"))->toHtml())); ?>');
        modal.showCenter();
    }
</script>
