<script>
    var today = new Date();
    today.setTime(today.getTime());
    var duration = 1000 * 60 * 60 * 24 * 365;    // @todo: Make this configurable (?)
    var expireDate = new Date(today.getTime() + duration);
    Mage.Cookies.expires = expireDate;
    if (!Mage.Cookies.get('seenModal')) {
        Mage.Cookies.set('seenModal', 1);
        modal = new Window({});
        modal.getContent().update("<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('cms/modal/block'))->toHtml(); ?>");
        modal.showCenter();

    }
</script>
